# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/apps/project-1"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      project1:
        applies-to: version-updates
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/apps/project-2"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      project2:
        applies-to: version-updates
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
